#
#  Copyright (c) 2017 Roku, Inc. All rights reserved.
#  Simple Makefile for Roku Channel Development
#

APPNAME = Transport Control Voice Sample Update
ZIP_EXCLUDE_LOCAL= .DS_Store /out

include ../../../app.mk
